### ISSUE TITLE
Hide mini-map on toggle

### ISSUE THREAD

**Issue by aaronmaynard** [aaronmaynard/ROSDashboard#1]
## 📦  Project: UI Settings

This issue is a good first issue for those looking to get into git, project collaboration, or html/javascript in general.   It is tied to the respective [project page](https://github.com/users/aaronmaynard/projects/1) and will be automatically sorted.
❤️ Thanks for helping!

## 📋  Issue:

Sometimes a user may not want to display a mini-map on their screen to maximize the space available for the video stream.  The goal of this issue is to change the existing code to make that happen!  

![Here](https://i.imgur.com/mN3lhDH.png "Settings Page")

The base of the code can be found in /js/mod.js

```
function toggleJoy() {
  var x = document.getElementById("joystick");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}

function toggleMiniMap() {
  var x = document.getElementById("mini-map");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
```

#### Helpful Hint:
There is already an event listener which is currently looking for a checkbox state change that toggles the on-screen joystick. 

## 👥  Contributing:

-  Comment in this issue that you would like to do it.
-  Open the ROSDashboard GitHub page and click the ★ Star and then ⑂ Fork buttons.
-  Once you've made sure all your changes work correctly and committed all your changes,
-  Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/ROSDashboard) and create a pull request for your changes.
-  Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #1)
-  Please <b>do not fix more than one issue at a time</b>. Your pull request should only fix what is described in this issue.

## 🆘  Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community.
If you need any help, feel free to ask below. We are always happy to help 😄

**Comment by Girishbari** [comment]
Let me do it , Please assign it to me

**Comment by realrohitgurav** [comment]
Can I contribute to this issue? @aaronmaynard
