### ISSUE TITLE
Add onClick() events for the AUX buttons

### ISSUE THREAD

**Issue by aaronmaynard** [aaronmaynard/ROSDashboard#2]
## 📦  Project: UI Settings

This issue is a good first issue for those looking to get into git, project collaboration, or html/javascript in general.   It is tied to the respective [project page](https://github.com/users/aaronmaynard/projects/1) and will be automatically sorted.
❤️ Thanks for helping!

## 📋  Issue:

The auxiliary buttons need to be able to do something! For now, make them display a message in the browser console.log(), informing which button was pressed.  The functions will later be used to send ROS messages, but that's an issue for another time.

![Here](https://i.imgur.com/YRMkuH1.png "AUX Buttons")

Non-ROS based code such as this can be added in /js/mod.js.  Each button in index.html that needs an onclick function is can be found below.

```
<!-- CENTRAL BUTTONS -->
<div class="auxButtons uiElement">
	<button class="buttonAux" onclick=""><span>Y</span><span>AUX 1</span></button>
	<br>
	<button class="buttonAux" onclick=""><span>X</span><span>AUX 2</span></button>
	<button class="buttonAux" onclick=""><span>B</span><span>AUX 3</span></button>
	<br>
	<button class="buttonAux" onclick=""><span>A</span><span>AUX 4</span></button>
</div>
```

#### Helpful Hint:
W3schools has a great tutorial on the onclick event. https://www.w3schools.com/jsref/event_onclick.asp 

## 👥  Contributing:

-  Comment in this issue that you would like to do it.
-  Open the ROSDashboard GitHub page and click the ★ Star and then ⑂ Fork buttons.
-  Once you've made sure all your changes work correctly and committed all your changes,
-  Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/ROSDashboard) and create a pull request for your changes.
-  Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #2)
-  Please <b>do not fix more than one issue at a time</b>. Your pull request should only fix what is described in this issue.

## 🆘  Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community.
If you need any help, feel free to ask below. We are always happy to help 😄

**Comment by magedbebawy** [comment]
Can I work on this issue?
